mmc: dw_mmc: [XJ3-2494]fix error message accessing NULL pointer
Summary:
Error: kernel panic when dw_mci error message
trying to access host->cmd which is NULL, error messages is produced
when an unfinished command timeout is detected, possibly from previous
SD card insertion.

Fix: by adding value check.

Test Plan: release hotpulg sd card okay

Reviewers: haipeng.yu

Differential Revision: https://cr.hobot.cc/D68138